# SPDX-FileCopyrightText: Copyright (c) 2025 Objectionary.com
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
name: deep
'on':
  push:
    branches:
      - master
    paths-ignore: [ 'README.md' ]
concurrency:
  group: aws-${{ github.ref }}
  cancel-in-progress: true
jobs:
  start-instance:
    runs-on: ubuntu-24.04
    outputs:
      label: ${{ steps.start.outputs.label }}
      ec2-instance-id: ${{ steps.start.outputs.ec2-instance-id }}
    steps:
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET }}
          aws-region: ${{ secrets.AWS_REGION }}
      - id: start
        uses: machulav/ec2-github-runner@v2
        with:
          mode: start
          aws-resource-tags: '[{"Key":"Name","Value":"speedment"}]'
          github-token: ${{ secrets.AWS_PAT }}
          ec2-image-id: ${{ secrets.AWS_AMI }}
          ec2-instance-type: c5.metal
          subnet-id: ${{ secrets.AWS_SUBNET }}
          security-group-id: ${{ secrets.AWS_SGROUP }}
  deep:
    runs-on: ubuntu-24.04
    timeout-minutes: 300
    steps:
      - uses: actions/checkout@v5
      - run: |
          sudo wget -q -O /usr/bin/phino http://phino.objectionary.com/releases/ubuntu-24.04/phino-latest
          sudo chmod a+x /usr/bin/phino
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3
      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: 23
      - uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ubuntu-jdk-21-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ubuntu-jdk-21-maven-
      - run: |
          git clone https://github.com/yegor256/aggregate-repeated-test
          mvn --file aggregate-repeated-test/pom.xml clean install -DskipTests
      - run: |
          mvn clean test -Dhone.skip=true
          mv /tmp/aggregate-repeated-test.txt before.txt
          mvn clean test -Dhone.skip=false
          mv /tmp/aggregate-repeated-test.txt after.txt
          ./join.rb before.txt after.txt
  terminate-instance:
    needs:
      - start-instance
      - deep
    runs-on: ubuntu-24.04
    if: ${{ always() }}
    steps:
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET }}
          aws-region: ${{ secrets.AWS_REGION }}
      - uses: machulav/ec2-github-runner@v2
        with:
          mode: stop
          github-token: ${{ secrets.AWS_PAT }}
          label: ${{ needs.start-instance.outputs.label }}
          ec2-instance-id: ${{ needs.start-instance.outputs.ec2-instance-id }}
